language: python

python:
  - "2.7"
  - "3.6"

install:
  - pip install coverage
  - pip install coveralls

script:
  - coverage run --source . test_generate_nhs_numbers.py

after_success:
  - coveralls
