---
name: unit-test action
on:
  pull_request:
  push:
    branches:
      # Run on merge to main because caches are inherited from parent branches
      - main
jobs:
  two_job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: ['2.7']
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python_version }}
      - name: Install package
        shell: bash
        run: |
          python -m pip install .
          python -m pip install mock
      - name: Run tests
        shell: bash
        run: |
          python tests/test_generate_nhs_numbers.py
  three_job:
    # Later versions don't support Python 3.6
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python_version: ['3.6', '3.7', '3.8', '3.9', '3.10']
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python_version }}
      - name: Install package
        shell: bash
        run: |
          python -m pip install .
      - name: Run tests
        shell: bash
        run: |
          python tests/test_generate_nhs_numbers.py
  coverage_job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: ['3.11']
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python_version }}
      - name: Install package
        shell: bash
        run: |
          python -m pip install .
          python -m pip install coverage
      - name: Run tests
        shell: bash
        run: |
          python -m coverage run --source nhs_number_generator tests/test_generate_nhs_numbers.py
          python -m coverage report --show-missing
      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v2
